features:added routing and also toggle sidebar
0silverback0/TrainerAppFrontend pull request #8
Opened 2023-10-22 18:25 UTC by weberankit

what I have done:-
added routing and arrange component

toggle sidebar

https://github.com/0silverback0/TrainerAppFrontend/assets/94105514/45ddaedd-2eb2-4fb6-bc91-cc426f2d81c2

2023-10-22 18:29 UTC, weberankit commented
I have also changed the arrangement of component a/c to routing following best practices and it is the most convenient and best way to do...  solved  issue #7

2023-10-22 18:39 UTC, 0silverback0 commented
im getting some redirect issues i think its a netlify issue honestly because ive had this problem before using router on netlify I want to see if this can be fixed before i merge

2023-10-22 18:59 UTC, weberankit commented
okay

2023-10-22 19:06 UTC, 0silverback0 commented
have you encountered an error before using react router on netlify?

2023-10-22 19:12 UTC, weberankit commented
@0silverback0 no could you plz send the screenshot of the error or tell me more about an error I will try to fix it

2023-10-22 19:32 UTC, 0silverback0 requested changes

2023-10-22 19:32 UTC, 0silverback0 commented on src/App.js
>  import Header from './Header';
its here header is defined but never used is the error. this may or may not fix the issue that just the current error

2023-10-24 03:55 UTC, weberankit commented
@0silverback0  plz check it (Header import deleted)

2023-10-24 04:18 UTC, weberankit commented
@0silverback0 Error is fixed How?
checkout this link https://githubsite.netlify.app/
what I have done is 
removed the build from gitignore file and run the command npm run build and I have manually deployed that build file on Netlify 

if you allow me then I will make pr but plz note that pr contains the build file also 
![image](https://github.com/0silverback0/TrainerAppFrontend/assets/94105514/65356cf2-eb9c-4a31-9c53-a20f066f0185)

2023-10-24 04:22 UTC, weberankit commented
or should I make PR by removing the build file as you like I will do it.

2023-10-24 11:14 UTC, 0silverback0 commented
nope that works thank you so much!

2023-10-24 11:16 UTC, merged